---
# Sample dev user â€” host_vars or group_vars should define dev_users.

dev_users:
  - name: devuser
    primary_group: devuser
    extra_groups:
      - wheel
    home: /home/devuser
    github_keys_url: "https://github.com/devuser.keys"


# HashiCorp repository configuration
hashicorp_repo_baseurl: "https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable"
hashicorp_repo_gpgkey: "https://rpm.releases.hashicorp.com/gpg"
hashicorp_repo_enabled: true
hashicorp_repo_gpgcheck: true
hashicorp_repo_repo_gpgcheck: true

# HashiCorp packages to install
hashicorp_packages:
  - terraform
  - packer

# General dev tool packages
dev_tool_packages:
  - acl
  - git
  - vim
  - tmux
  - golang
  - nmap-ncat
  - sshpass

# Virtualization packages for KVM/libvirt
virtualization_packages:
  - qemu-kvm
  - libvirt
  - libvirt-daemon-kvm
  - virt-install
  - virt-manager

# Hugo static site generator (extended version for SCSS/search support)
# Get checksum from: https://github.com/gohugoio/hugo/releases/download/vX.X.X/hugo_X.X.X_checksums.txt
hugo_version: "0.140.1"
hugo_tarball_url: "https://github.com/gohugoio/hugo/releases/download/v{{ hugo_version }}/hugo_extended_{{ hugo_version }}_linux-amd64.tar.gz"
hugo_tarball_sha256: "7eef6ee9143add2827e29eac370ee4e39f9d2edddc83539c7e9f3fead7e0f72f"