---
- name: Install dev tools
  ansible.builtin.import_tasks: dev_tools.yml

- name: Deploy users
  ansible.builtin.import_tasks: deploy_users.yml

- name: Install web tools
  ansible.builtin.import_tasks: web_tools.yml

- name: Install Hashicorp tools
  ansible.builtin.import_tasks: hashicorp_tools.yml

- name: Install AI tools
  ansible.builtin.import_tasks: ai_tools.yml

- name: Setup virtualization
  ansible.builtin.import_tasks: virtualization.yml

- name: Image Builder Prereqs
  ansible.builtin.import_tasks: image_build_prereqs.yml