- hosts: builder
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstation

- hosts: artifact_servers
  become: true
  roles:
    - artifacts

- hosts: network_controllers
  become: true
  roles:
    - omada_controller

- hosts: bootstrap_nodes
  become: true
  roles:
    - bootstrap
